#define WORLD_FLAG_DoMeshSkinning     (1u << 0u)
#define WORLD_FLAG_UseInstanceBuffer  (1u << 1u)
#define WORLD_FLAG_SampleTexDiffuse   (1u << 2u)
#define WORLD_FLAG_SampleTexNormal    (1u << 3u)
#define WORLD_FLAG_SampleTexRoughness (1u << 4u)
